### ISSUE TITLE
A problem regarding inference and visulization

### ISSUE THREAD

**Issue by kagawa588** [fredzzhang/pvic#46]
Hi Sir,
Thanks for your great work! 
When I run the inference code, I met the following issue, could you pls give me any advice?

=> Start from a randomly initialised model
Traceback (most recent call last):
  File "inference.py", line 164, in <module>
    main(args)
  File "/home/user/miniconda/envs/torch/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "inference.py", line 121, in main
    image, output[0], attn_weights[0],
IndexError: list index out of range
(torch) ➜  pvic git:(main) ✗

**Comment by fredzzhang** [comment]
Hi @kagawa588,

You are using a randomly initialised model. Make sure to check that the checkpoint path is correct.

Fred.
